### ISSUE TITLE
[BUG]: Generated test workflow incorrectly uses `always`

### ISSUE THREAD

**Issue by tmelliottjr** [octokit/create-octokit-project.js#213]
### What happened?

The generated `test.yml` workflow incorrectly uses `always`. Instead it should use `always()`.

See relevant [documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#always).

### Versions

2.3.3

### Relevant log output

```shell
The workflow is not valid. .github/workflows/test.yml (Line: 35, Col: 9): Unrecognized named-value: 'always'. Located at position 1 within expression: always
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tmelliottjr** [comment]
@gr2m I'm happy to open a pull for this.

**Comment by gr2m** [comment]
> @gr2m I'm happy to open a pull for this.

please do <3
