### ISSUE TITLE
CONTRIBUTING: cleare separate section for maintainers only

### ISSUE THREAD

**Issue by gr2m** [octokit/create-octokit-project.js#74]
The "Merging the Pull Request & releasing a new version" is for maintainers only, we should make that more clear

**Comment by dominguezcelada** [comment]
What was the issue with this? (any confusion with contributors so it is needed to improve this description?), also, what do you have in mind? Just **highlighting** a disclaimer for that section saying is for maintainers only?

**Comment by gr2m** [comment]
good questions, I should have been more clear. It was a question by someone who wanted to send a pull request to `@octokit/rest` documentation but didn't understand the commit conventions. If it was clear that these are only relevant to maintainers then the problem would not have occured.

I think I would add a new header `## Maintainers only` here: https://github.com/octokit/create-octokit-project.js/blob/51f5a550d8fb98344dec3fdc2dd130de7c823410/lib/create-contributing.js#L62-L77

and then make the current heading level 3: `### Merging the Pull Request & releasing a new version`. That should be clear enough?

**Comment by dominguezcelada** [comment]
> good questions, I should have been more clear. It was a question by someone who wanted to send a pull request to `@octokit/rest` documentation but didn't understand the commit conventions. If it was clear that these are only relevant to maintainers then the problem would not have occured.
> 
> I think I would add a new header `## Maintainers only` here:
> 
> https://github.com/octokit/create-octokit-project.js/blob/51f5a550d8fb98344dec3fdc2dd130de7c823410/lib/create-contributing.js#L62-L77
> 
> and then make the current heading level 3: `### Merging the Pull Request & releasing a new version`. That should be clear enough?

Yep. I guess this a `goodfirstissue`, should we leave it? Or just PR it?

**Comment by gr2m** [comment]
I'd PR it in this case, because this is such a meta repository
