### ISSUE TITLE
add renovate configuration to Repository if repository is in @octokit

### ISSUE THREAD

**Issue by gr2m** [octokit/create-octokit-project.js#98]

**Comment by oscard0m** [comment]
With latest changes on update ecosystem, should we reformulate this issue to GitHub Actions listening to custom dispatched events? Or... since it depends on the whole ecosystem of GitHub Actions, GitHub App, etc, we should not consider this anymore?

**Comment by oscard0m** [comment]
> sorry I should have clarified this issue a bit more. It's about adding these lines to `package.json` if the target repository is created in the @octokit organization:
> 
> https://github.com/octokit/octokit.js/blob/dcc96e746bc948faeb3f7d6875d12fd269c3f3c0/package.json#L112-L116
> 
> as we use renovate for all dependency updates in @octokit.

[As @wolfy1339's pointed](https://github.com/octokit/plugin-paginate-graphql.js/pull/4#issuecomment-1166527681), storing Renovate config in `package.json` [is deprecated](https://docs.renovatebot.com/configuration-options/).

I would use `renovate.json` instead.

**Comment by wolfy1339** [comment]
Should we store it in the `.github` folder?

**Comment by oscard0m** [comment]
> Should we store it in the `.github` folder?

I don't have any preference.

**Comment by gr2m** [comment]
yes please let's put it in `.github`

**Comment by oscard0m** [comment]
I added some missing logic to [`@octoherd/script-setup-renovate`](https://github.com/octoherd/script-setup-renovate). I think we are ready to run this across the repos of the org you would like to have Renovate.

I noticed it creates/updates `.json` removing the new lines and spaces completely, is this a blocker to our use-case? (see https://github.com/octoherd/script-setup-renovate/pull/29).

The script requires a token with privileges to push directly on the `defaultBranch` branch.

---

Pending to do the removal of `pkg.renovate` entry from `package.json`. I'm assuming `.github/renovate.json` [will take precedence according to Renovate Documentation](https://docs.renovatebot.com/configuration-options/).

**Comment by gr2m** [comment]
So there are two things we need to do, if I get it correctly

1. move the renovate configuration in current @octokit repositories from the `package.json` files to `.github/renovate.json` (as we just did in @probot)
2. Create a `.github/renovate.json` file when running `npm init octokit-project` and creating a @octokit repositor (this is the original scope of this issue)

Did I get this right?

I can run the scripts to conclude step 1 if everything is ready @oscard0m

**Comment by oscard0m** [comment]
> So there are two things we need to do, if I get it correctly
> 
> 
> 
> 1. move the renovate configuration in current @octokit repositories from the `package.json` files to `.github/renovate.json` (as we just did in @probot)
> 
> 2. Create a `.github/renovate.json` file when running `npm init octokit-project` and creating a @octokit repositor (this is the original scope of this issue)
> 
> 
> 
> Did I get this right?
> 
> 
> 
> I can run the scripts to conclude step 1 if everything is ready @oscard0m 

The steps are correct and scripts are ready.

**Comment by gr2m** [comment]
I updated all @octokit repositories. Only thing left now is

> Create a .github/renovate.json file when running npm init octokit-project and creating a https://github.com/octokit repositor (this is the original scope of this issue)
